import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=path=>fs.readFileSync(new URL('../'+path,import.meta.url),'utf8');
const page=read('indexes/library/index.html'),script=read('assets/js/corbanu-index-library.js'),ui=read('assets/js/corbanu-index-ui.js');
assert.ok(page.includes('id="index-library-grid"'));
assert.ok(page.includes('id="library-search"'));
assert.ok(page.includes('id="library-sort"'));
assert.ok(script.includes('/v2/indexes/published'));
assert.ok(script.includes('Expand holdings'));
assert.ok(script.includes('Performance ranking is not yet tracked'));
assert.ok(ui.includes('reasoning_block'));
assert.ok(ui.includes('Portfolio weights'));
assert.ok(ui.includes('api.corbanu.com'));
assert.equal(script.includes('trycloudflare.com'),false);
assert.equal(script.includes('innerHTML'),false);
assert.ok(read('indexes/index.html').includes('href="/indexes/library/"'));
assert.ok(read('api/index.html').includes('id="indexes"'));
assert.ok(read('api/index.html').includes('/v2/indexes/previews/$INDEX_ID/result'));
